version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./s3_credentials:/app/s3_credentials
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
